[package]
name = "lcms2"
version = "0.1.0"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
keywords = ["icc", "profile", "color", "lcms"]
include = ["src/**/*", "tests/**/*", "examples/**/*", "Cargo.toml", "README.md"]
description = "ICC color profile handling. Rusty wrapper Little CMS"
readme = "README.md"
license = "MIT"
documentation = "https://pornel.github.io/rust-lcms2/lcms2/"

[dependencies]
lcms2-sys = "0.4"
