[package]
name = "lcms2"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
keywords = ["icc", "profile", "color", "lcms"]
include = ["src/**/*", "tests/**/*", "examples/**/*", "Cargo.toml", "README.md"]
description = "ICC color profile handling. Rusty wrapper Little CMS"
readme = "README.md"
license = "MIT"
documentation = "https://pornel.github.io/rust-lcms2/lcms2/"
repository = "https://github.com/pornel/rust-lcms2.git"
categories = ["multimedia::images", "api-bindings"]
version = "4.2.0"

[dependencies]
foreign-types = "0.2.0"
lcms2-sys = "2.4.4"

[features]
static = ["lcms2-sys/static"]
